added mbc3 tester
c-sp/gameboy-test-roms pull request #28
Opened 2024-02-10 19:59 UTC by vojty

2024-02-11 09:52 UTC, c-sp requested changes
Thanks for your efforts and the quite thorough PR!

I would like to suggest the following changes:

- Most test suites' screenshots are created using the color palette described [here](https://github.com/c-sp/gameboy-test-roms/blob/master/src/howto/dmg-acid2.md#test-successfailure). Could you change color `#C0C0C0` to `#AAAAAA`?
- Could you add a screenshot for "CGB compatibility" mode? Replacing color `#C0C0C0` with `#7BFF31` should be sufficient for this.
- Could you rename `game.gb` to e.g. `mbc3-tester.gb`?

2024-02-12 07:21 UTC, vojty commented
Sure no problem!

2024-02-12 15:11 UTC, vojty commented on src/howto/mbc3-tester.md
> +  - objects: `#000000`, `#943939`, `#FF8484` and `#FFFFFF`
I copy & pasted this line from acid, maybe I can drop the colors for objects

2024-02-12 15:11 UTC, vojty commented
fixed

2024-02-12 18:30 UTC, c-sp commented
Great, thanks a lot!

No need to adjust the color paragraph in my opinion.

2024-02-12 19:36 UTC, vojty commented
alright, let's merge it so I can add the others as well

2024-02-12 20:03 UTC, merged